### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by richgel999** [nlguillemot/CppSPMD#2]
Hi - I can't find a license for CppSPMD, particularly the most important file (common/spmd_avx2-i32x8.h). It would be great if you choose a very liberal license (like zlib, Apache 2.0, MIT, or public domain). If you choose a restrictive license (GPL, LGPL) I will have to rewrite all the code, which won't be fun.

Thanks!
-Rich

**Comment by nlguillemot** [comment]
Thanks for the reminder. I retroactively added an MIT license. I would like to warn though that I can't say that this is ready for production as-is. There are probably bugs.

**Comment by richgel999** [comment]
Thank you very much! I will go and update the license on my downstream version. I have mostly rewritten it, and it's working wonderfully. All the core ideas carried forward without any issues, and there were very few bugs. Thank you for releasing such a useful project!

**Comment by dumblob** [comment]
>All the core ideas carried forward without any issues, and there were very few bugs.

@richgel999 if you already spent the time to fix some bugs, could make a PR in this repo, so that the bugs get fixed also here in "upstream"?

**Comment by nlguillemot** [comment]
I would personally suggest to make a separately maintained fork.

**Comment by richgel999** [comment]
As I've changed most of the code in my version, a fork is best:
https://github.com/richgel999/CppSPMD_Fast

I'll have AVX-512 support in soon.
