### ISSUE TITLE
Would you be willing to change to the Apache 2.0 license?

### ISSUE THREAD

**Issue by richgel999** [nlguillemot/CppSPMD#3]
Hi Nicolas - We're going to release an update to the open source Basis Universal library early next month that supports SSE. It internally uses kernels written using cppspmd (via cppspmd_fast). The current license is MIT, which causes us and our users to jump through some extra hoops on the legal side (almost all our code is Apache 2.0). Would you be willing to re-release cppspmd using Apache 2.0, or give us permission to change the original license from MIT to Apache 2.0?

Thank you,
Richard Geldreich - Binomial LLC

**Comment by nlguillemot** [comment]
Hi Rich, definitely feel free to tweak the license to your use.

**Comment by richgel999** [comment]
Thanks! It's up:
https://github.com/BinomialLLC/basis_universal/
